alias: "Automation 3_ Turn On Heat Mode"
description: If heat mode is turned on, then turn off cool mode, and set the temperature to 24 °C.
trigger:
  - platform: state
    entity_id:
      - input_boolean.heat
    from: "off"
    to: "on"
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.cool
  - service: input_number.set_value
    data:
      value: 24
    target:
      entity_id: input_number.ac_temperature
  - service: button.press
    data: {}
    target:
      entity_id: button.orange2
mode: single
